language: node_js
node_js:
  - "0.12"
sudo: false
before_install:
  - "git clone https://github.com/google/closure-linter ~/gjslint && (cd ~/gjslint; python ./setup.py install)"
  - "git clone https://github.com/Samsung/jalangi2 ~/jalangi2 && (cd ~/jalangi2; npm install)"
before_script:
  gjslint ./sherlock.js
env:
  - jalangi=~/jalangi2
addons:
  apt:
    packages:
    - python-software-properties
    - python
    - make